default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ryde_development
  username: ryde_admin
  password: password

staging:
  <<: *default
  database: ryde_staging
  username: ryde_admin
  password: password

production:
  <<: *default
  database: ryde_production
  username: ryde_admin
  password: password

test:
  <<: *default
  database: ryde_test